README.md
I write a first draft of the initial page of our Rest contract to move thing ahead and facilitate more discussion.
Probably it will be better to split the different sections in dedicated sub-pages. I have reserved the (not yet created) endpoints.md page for the discussion around each endpoint but I have preferred to keep all the other things in a single page at the start so that anyone can fastly check "the whole"
=> Initial draft of the major area of the rest contract

README.md, endpoints.md, projections.md, search-rels.md
The main README file contains guidance about the framework and the technical approach to be followed.
I am proposing the addition of some detail files to facilitate brainstorming of additional development that is needed.
Question: Could/Should this documentation move into the the main code repository rather than residing in DSpace-Labs?
=> Add Documentation Component Files

endpoints.md, search-rels.md
I am submitting this PR to generate additional conversation about features that need to be implemented.
=> Additional brainstorming about REST functionality that needs to be created

authorities.md, endpoints.md, submissiondefinitions.md, submissionforms.md, submissionsections.md
As result of the implementation proposed in https://github.com/DSpace/DSpace/pull/1852 some small changes to the contract are required. They are needed to keep the contract uniform between different endpoints and make the implementation easier
- removed the minus in the endpoint urls, all the endpoints are lowercase
- the type attribute is reserved for the name of the REST resource.
- introduced the sectionType
- count goes in the extraInformation section of the authority entry
=> DS-3699 small fix to align the actual implementation with the contract

endpoints.md, submissionsections.md, workspaceitems.md
This PR formalize the contract requested in https://jira.duraspace.org/browse/DS-3743
Please note the different format used here to represent the metadata compared to the format used in all the other endpoints. 
Essentially each metadata becomes a separate attribute of the JSON serialization instead to have a single array with all the metadata together. This change is needed to allow partial updates via PATCH request in JSON Patch or Merge JSON Patch format.
The kinds of partial updates that can be supported with this format are
- set of a single metadata (clean, add additional values, remove values or reorder values)
- set multiple metadata at once
without sending (and know) any information related to the metadata (and the other aspects) that don't need to be updated.
This format for the …
=> DS-3743 initial draft of the workspaceitems contract

browses.md
The BrowseEntry Resource defines a NAME constant with value BrowseEntry this imply that the resource collection endpoint should expose the list in the _embedded section using the browseEntries name.
This was previously ignored due to a bug in the JAVA implementation fixed in the commit
https://github.com/DSpace/DSpace/pull/1889/commits/e386f0d49ec04f528c5bfd8309143df75736a99f
=> align the contract to the name convention set in the java project

README.md, collections.md, endpoints.md, patch.md, resourcepolicies.md, search-rels.md, submissionsection-types.md, submissionsections.md, submissionuploads.md, workspaceitem-data-license.md, workspaceitem-data-metadata.md, workspaceitem-data-upload.md, workspaceitems.md
This PR adds lot of documentation to our existent REST contract with a focus on the PATCH method for the workspaceitem but also covering some existent endpoint that were not previously documented or extending existent documentation.
IMHO the best way to review is to navigate the remote branch as you will see the rendered markdown  https://github.com/4Science/Rest7Contract/tree/DS-3759
Please note that this is what we plan to implement in https://github.com/DSpace/DSpace/pull/1889 we are close to have it properly implemented but in the current implementation we have take some shortcut to be able to demonstrate it also if it is not yet perfect
=> DS-3759 the patch method for the workspaceitem

claimedtasks.md, polltasks.md, workflowitems.md
This is a starting point proposal for the contract of the workflow endpoints in the new REST API.
The implementation of a workflow state machine actions is widely debated question and there are lot of discussion about the best way to implement them in a RESTful way or criticism about which implementation is not really RESTful.
This is a good summary of the different possible approaches
http://www.kennethlange.com/posts/Modeling-Workflows-in-REST-APIs.html
these are also useful resource to listen different opinions, pro and contros
https://restful-api-design.readthedocs.io/en/latest/methods.html#actions
https://github.com/interagent/http-api-design/issues/58
https://www.gvj-web.com/blog/custom-actions-your-rest-api
At the end my preferred approach is in the middle between the approach "2. …
=> DS-3851 initial proposal for the workflow endpoints

browses.md
To support the Jump To feature in the browses we need to introduce a new parameter to "compute" on the fly the new offset.
At the least two different options exists:
1) we can add a separate endpoint to compute the offset and leave to the client to deal with it and package a right pagination request after to have retrieved the offset. This is inefficient as require one more round trip between client and server
2) add a startsWith parameter. This is the easier solution on the REST contract. We only need to decide how to deal with inconsistent request where multiple pagination criteria are included (i.e. page and startsWith). My suggestion is to reject such requests with a 422 response code
=> Add error codes and support for jump to

search-endpoint.md
This PR (kudos to @Raf-atmire) aligns the DSpace REST API Search contract with additional fields to make the life of our Angular UI developers easier. 
It also corrects the pagination of search results so that pagination information (fields + links) are present on the correct level.
=> Align REST Search contract with Angular UI requirements

items.md
Only describes the replace operation since that is what has been implemented to date.  Will (or may) define other operations after consultation with project leaders.
=> Updated item documentation with information on the patch operation.

endpoints.md, item-requests.md
See https://github.com/DSpace/DSpace/pull/2129#discussion_r228649365
=> [DS-3952] Rename item copy request endpoint from 'copyrequests' to 'itemrequests'.

items.md
There are a few very minor issues with the example curl request to make an item private. This PR addresses these issues. (Tested with curl 7.54.0)
=> Small fix in the make "item private" curl example

metadatafields.md, metadataschemas.md
This PR includes alterations to the metadata schema/field contracts to support creating, updating & deleting schemas/fields.
The update currently uses PUT as a framework for PATCH is still in the works.
=> Updating metadata registry rest contracts to support CRUD

README.md
This is the beginnings of some cleanup to the REST Contract README.  Once reviewed/approved, it can be merged as-is (and I can always follow-up with more PRs).
Mostly, this tries to better define the terminology used (resource, collection, object, association) in our contract. It also documents the `422` response code (which was requested in PR #33 comments)
=> Add Design Principles, terminology, examples to README

search-rels.md
This is an enhancement to better describe how we expect `/api/core/{model}/search` endpoints to respond, and linking in some examples.
=> Enhance description of Search endpoints. Link in examples.

items.md
This is a quick fix for a typo in the above examples (followup of #36 )
=> Fix curl examples for withdrawn and discoverable

README.md, items.md
Replacement for #35 (@benbosman and @KevinVdV) and #44 (@abollini). 
This PR includes alterations to the items.md contract to add for mapping of items to collections.
JIRA: https://jira.duraspace.org/browse/DS-4097
I've attempted to bring in feedback from both prior PRs. Here's what I've done:
**BEFORE WE CAN MERGE THIS**
One outstanding question remains...we have a discrepancy on the `DELETE` method format:
* #35 expects DELETE to use "text/uri-list" (like PUT and POST)
* #44 expects DELETE to use `items/[:uuid]/mappedCollections/[:uuid_of_collection_to_remove]`
In the Spring Data REST community, they seem to recommend using `PUT` for deletion (by calling `PUT` with an empty body). See: https://stackoverflow.com/a/28713232/3750035  Though, there's also an answer more like #44 here: …
=> Mapping collection

README.md, bitstreams.md, collections.md, communities.md, epersons.md, items.md, metadata-patch.md, workspaceitem-data-metadata.md
This adds contract docs for metadata PATCH support.
https://jira.duraspace.org/browse/DS-3908
It mainly just adds this document and links to it from appropriate places: https://github.com/DSpace/Rest7Contract/blob/0f04637d0ca16e42ad1fcce251e17db49b0fb701/metadata-patch.md
REST implementation PR: https://github.com/DSpace/DSpace/pull/2313
=> DS-3908 Metadata patch support

epersons.md
This is related to https://github.com/DSpace/DSpace/pull/2257, which gives logged in users the ability to update their eperson profile. That includes the ability to update metadata on the eperson DSO.
Both PR's appear to be in conflict with https://github.com/DSpace/Rest7Contract/pull/46 and work on metadata patches by cwilper. If that approach is taken then I think this PR (and it's related PR) will become smaller in scope, since the only new feature provided is giving logged in users the ability to change their password.
=> [DS-4062] Endpoint for eperson profile patches

collections.md, communities.md
DS-4107 contract changes were already approved in https://github.com/DSpace/Rest7Contract/pull/39
This new PR just cleans up some subsequently merged JSON that did not use the new, correct structure.
=> DS-4107 Fix collection/community examples to use new metadata structure

README.md, bitstreams.md, collections.md, communities.md, epersons.md, items.md, metadata-patch.md, search-rels.md, workspaceitem-data-metadata.md
This is a Pull Request in the configurable entities branch
The item metadata wasn't revealing the place column yet in https://github.com/DSpace/Rest7Contract/pull/39
This was however present in configurable entities as part of https://github.com/DSpace/DSpace/pull/2331:
```json
{
"metadata": [
{
"key": "dc.contributor.author",
"value": "Simmons, Cameron",
"language": "*",
"place": 0,
"authority": "virtual::732",
"confidence": -1
},
{
"key": "dc.contributor.author",
"value": "Plain text author",
"language": null,
"place": 1,
"authority": null,
"confidence": -1
},
{
"key": "dc.contributor.author",
"value": "Plain text author 2",
"language": null,
"place": 2,
"authority": null,
"confidence": -1
},
{
"key": "relation.isAuthorOfPublication",
"value": "0ffbee3f-e7ea-42bc-92fe-2fbef1a52c0f", …
```
=> Configurable Entities - Item metadata place

relationships.md
Based on https://jira.duraspace.org/browse/DS-4230, the PUT contract in the relationships has been updated to use /api/core/relationships/:id/leftItem or /api/core/relationships/:id/rightItem
=> DS-4230 - PUT contract in relationships

search-endpoint.md
As by discussion in https://github.com/DSpace/DSpace/pull/2377 it seems that we should add to the REST contract our decision about the query parameter to be alway treated as a lucene query
=> DS-4191 make explicit the need to escape special chars

submissionforms.md
Example of a closed and open relationship in the submission forms
This has been discussed in the entities meeting, and is documented at https://docs.google.com/document/d/1X0XsppZYOtPtbmq7yXwmu7FbMAfLxxOCONbw0_rl7jY/edit#heading=h.5bu9shx0j942 and https://docs.google.com/document/d/1X0XsppZYOtPtbmq7yXwmu7FbMAfLxxOCONbw0_rl7jY/edit#heading=h.yf95g3tikk1j
=> support for defining relationship lookups in the submission forms

collections.md, endpoints.md, harvestermetadata.md, harvesting_metadata_configs.md
REST contract for viewing and configuring the OAI Harvesting settings of a collection.
This also includes an endpoint to retrieve a list of all configured supported harvesting formats.
This doesn't include starting the actual harvest action. It can be supported using https://github.com/DSpace/Rest7Contract/pull/17
=> OAI Harvesting configuration

submissionforms.md
This is a correction to https://github.com/DSpace/Rest7Contract/pull/64
The selectableRelationship was accidentally defined as an array (similar to selectableMetadata). Only one selectableRelationship was supposed to be used.
=> Defining relationships in submission forms: selectableRelationship should not be an array

relationships.md, relationshiptypes.md
This PR contains two minor changes to the REST contract:
* The leftLabel is renamed to leftWardLabel at the relationship type level to clarify e.g. isAuthorOfPublication is the name of the arrow pointing from the right item to the left item. The term leftLabel created some confusion in the past.
* Support for name variants has also been included with an leftWardLabel property at the relationship level to specify an alternative name used in the arrow pointing from the right item to the left item.
The name variants will be exposed in the virtual metadata as well, so this direct property will primarily be used for storing and updating the label.
=> Rename properties and support for name variants

bitstreams.md
The bitstream currently has a PATCH feature for the metadata, but doesn't support any other changes (e.g. changing the bitstream format)
This PR contains all changes which can be performed to a bitstream except for the bitstream order.
For the bitstream order, a separate PR will be created since the order is determined at the bundle level
=> Update bitstream properties and format

processes-endpoint.md, scripts-endpoint.md
This is a contract proposal for https://jira.duraspace.org/browse/DS-3763
DSpace offers functionality like import and export of metadata and items, running curation tasks, running an OAI harvest from the web UI. While we can implement each of these features as a dedicated endpoint, I think it would require the same effort to implement one generic endpoint that is able to run (REST-enabled) DSpace CLI scripts for the REST API.
I'm very interested to hear your thoughts on this.
=> DS-3763: Scripts and processes endpoint

items.md
This Rest Contract is a continuation of https://github.com/DSpace/Rest7Contract/pull/74
It ensures admins can create a new entity based on an external source.
This uses a POST on the /api/core/items, but instead of using a JSON content-type (with metadata), it uses a URI-list (with the collection and external source)
The item is immediately archived, making this only possible for admins
=> Entities: Creating an archived item from an external source

authentication.md, endpoints.md
To manage the discussion about the authorization mechanism we will need to propose little modification to the authentication endpoint, specifically to the claims exposed in the JWT.
For this reason and for consistency I reviewed the information currently available on the wiki including details about return codes and giving a structure to the information more similar to the other endpoints contract.
The wiki page is still needed as it includes information for DSpace developers (how to implement the security, how to add claims, etc.) the REST contract instead is for REST Client developers
=> Add authentication information in the REST contract

external-authority-sources.md
It might be useful to include the reference for the entry (parent) at entryValues HAL links:
```
"_links": {
"entry": {
"href": "https://localhost/server/api/integration/externalsources/orcidV2"
},
"self": {
"href": "https://localhost/server/api/integration/externalsources/orcidV2/entryValues/0000-0002-3503-4812"
}
}
```
=> adding entry HAL Link at entryValues level

endpoints.md, workflowdefinitions.md, workflowsteps.md
The configurable workflow supports configurable and customizable steps. Depending on the workflow step, different features are supported, and different buttons should be displayed.
The configuration should be exposed using the REST contract. This should ensure the UI will be able to identify whether Accept, Reject and/or Edit metadata buttons should be displayed for the basic steps.
More advanced workflow steps such as the select reviewer step and the score review step may need additional configuration, but that part has not been included for this initial REST Contract to keep the complexity limited.
Sample actions are already documented at https://github.com/DSpace/Rest7Contract/blob/master/claimedtasks.md#post-method-single-resource-level
=> Workflow step definitions

metadata-suggestions.md, workspaceitems.md
https://jira.duraspace.org/browse/DS-4281
This Rest Contract will introduce the live import from https://wiki.duraspace.org/dsdoc6x/using-dspace/ingesting-content-and-metadata/submission-user-interface/2016-framework-for-live-import-from-external-sources
This will allow the user to choose an external source to import from, retrieve suggestions, and apply the metadata changes once the user has confirmed the suggested changes are applicable.
This Rest Contract is related to https://github.com/DSpace/Rest7Contract/pull/74
It ensures a submission can be started based on an external source.
This uses a POST on the /api/submission/workspaceitems, with a URI-list (with the collection and external source).
The item metadata is imported in this case
=> DS-4281: Metadata suggestions in the live import

entitytypes.md
This PR contains two parts:
* Rename itemtypes to entitytypes. This was once suggested to be renamed to itemtypes but hereafter kept as entitytypes, and implemented as entitytypes, but the REST Contract was not reverted yet
* Add a REST contract to retrieve an entity type based on the label. This will correspond to org.dspace.content.service.EntityTypeService#findByEntityType. The syntax for this contract is based on https://stackoverflow.com/a/20386425
=> Entity type small changes

claimedtasks.md, pooltasks.md, workflowactions.md, workflowsteps.md
In the previous workflow contract, I had forgotten difference between a workflow step and a workflow action. A workflow step typically has only one workflow action (that's why I had forgotten about it), but multiple are possible.
I've adjusted the REST contract to make this differentiation
=> Workflow actions (update)

collections.md, communities.md
In order to display a trail (breadcrumb), the parent objects have to be known.
The item already has an owningCollection link, but this includes links for retrieving a collection's parent community and a community's parent community. This will be required to build the trail.
The actual implementation will require projections functionality to ensure the embedded data is limited
=> Support for a trail by retrieving parent objects

endpoints.md, items.md, version.md, versionhistory.md, workflowitems.md, workspaceitems.md
First iteration of the read-only parts of versioning, planned for beta 2
This will allow displaying the version history
=> Versioning

collections.md, communities.md, epersons.md, metadatafields.md
Add mention in the contract about the 400 return code where applicable.
Please note that most of the failing test after the switch from 422 to 400 where related to undocumented endpoint, here I have documented the current situation except than for the security of the findByEmail method where I suggested to add security checks, see https://jira.lyrasis.org/browse/DS-4431
=> fixed rest contracts concerning  DS-4428

projections.md
This just updates the old `projections.md` to bring it in line with the agreed implementation thus far.
=> DS-3533 Update projections contract to match impl

claimedtasks.md, pooltasks.md, workflowitems.md
This includes links from claimed tasks, pooled tasks and workflow items to the configured workflow steps and actions
This should eventually replace the json properties, but Angular will need a transition period to migrate from the properties to the HAL links
=> Link to workflow steps and actions

epersons.md
The DSpace 7 UI allows a user to modify their name and preferred language, which is stored as EPerson metadata.
This minor change should make sure the metadata (but still not email, netid, …) can be updated by a regular user as well
=> Edit profile: edit metadata

version.md
Removing the eperson embed & exposing the creator of the version under the "submitterName" property. We don't want to expose the eperson record of the creator of a version for privacy/security reasons. In DSpace 6 we only display the name of the submitter.
=> [version.md] Changing submitter availability

epersongroups.md
Adding 422 when attempting to delete a permanent group or a group that has a parent.
=> [epersongroups.md] Adding 422 for group deletes

authentication.md
The goal of the underlying implementation is:
* Login-as is migrated to an explicit AuthenticationMethod
* This AuthenticationMethod implementation will only act if the current user is an admin, and the login method is enabled (replacing the old `webui.user.assumelogin` boolean)
* It won't need a password, but still needs an email address or UUID
As part of the implementation, it would also be best to improve the EPersonRestAuthenticationProvider implementation, this will have an impact on the Angular UI as well:
* The Angular UI currently reads the WWW-Authenticate header to identify the `AuthenticationMethod` based on the getName() method
* If the Angular UI specifies which authentication method it attempts (posting to /server/api/authn/login with parameters method=password, user and …
=> Login-as using WWW-Authenticate

submissioncclicenses.md, submissionsection-types.md, workspaceitem-data-cclicense.md
This contains:
* Accessing the list of CC licenses based on the `cc.license.classfilter` configuration
* Representing the list of CC licenses and the fields (questions) per license
* Attaching the CC license (with answers to the questions) to the workspace item
* Verifying which CC license has been attached to the workspace item
=> CC License

authentication.md, bitstreams.md
This PR includes a new endpoint to retrieve short lived tokes that can be used for file downloads if the file is restricted.
The problems & the abstract description of the solution can be found here: https://github.com/DSpace/dspace-angular/issues/631
**Authenticating the token**
Authentication is currently done here: https://github.com/DSpace/DSpace/blob/master/dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessAuthenticationFilter.java#L120-L125, this calls on the "JWTTokenRestAuthenticationServiceImpl" to do the actual authentication. In the end the "JWTTokenHandler" class is called to provide / resolve the token, this "JWTTokenHandler" will become an abstract class with 2 implementations:
- JWTSessionTokenHandler
- JWTParameterTokenHandler
All code moves to the …
=> Download authorizations

submissioncclicenses.md
As mention in the PR: https://github.com/DSpace/DSpace/pull/2764, this PR will clarify the response of the **/api/config/submissioncclicenses/search/rightsByQuestions** endpoint.
=> [CC License support] Addingresponse to "rightsByQuestions"

authentication.md, bitstreams.md
This is a continuation of https://github.com/DSpace/Rest7Contract/pull/126, based on a problem identified in https://github.com/DSpace/DSpace/pull/2783#issuecomment-652248755
It renames the parameter from token to authentication-token
It also explicitly mentions which endpoints are not allowed to use the authentication-token
=> Authorization for Downloads of restricted Bitstreams: Short lived token endpoint

bundles.md
We noticed there's one "parent" link missing in all DSOs.  
A bitstream has a link to the bundle, an item has a link to the owning collection, …
This PR ensures the bundle also has a link to the item
This will also ensure the edit bitstream page can link back to the item (via the bundle)
=> Expose Item from Bundle

metadatafields.md
This solves https://github.com/DSpace/dspace-angular/issues/750
Instead of expecting Angular to load all metadata fields to filter, Angular just needs to load the first 10, and can send the query directly to REST when the user starts typing
=> Metadata field search

search-endpoint.md
This is a minor change to support e.g. /server/api/discover/search/objects?dsoType=Collection&dsoType=Community to return communities and collections
This allows the UI to display a search containing a mixture of communities and collections to perform a task which can apply to either
=> Discovery search: support multiple dsoType values

metadatafields.md
This is related to https://github.com/DSpace/DSpace/pull/2899#discussion_r462135920
For the front end validation on whether or not a filled in mdField is valid (on the edit item > metadata page) an exact retrieval of a mdField is needed, where either exactly one matching mdField is given or none if it doesn’t exist.
The findByName endpoint is far from ideal for this, it would have the drawbacks:
* For mdFields without a qualifier, it would need to be handled separately to determine there's no qualifier
* In frontend, it would need to be specified there's no qualifier
* Based the search results, the field has to be searched for, and no match implies it doesn't exist
For these use cases, the recommended Spring REST solution would be to create a separate non-search endpoint, retrieving the …
=> Metadata field: retrieve by exact name

processes-endpoint.md
The scripts and processes endpoints currently don't offer a search endpoint.
This contract change offers a search, so Angular can display a filtered list of processes
=> Search processes

README.md
Minor cleanup of the README for our REST Contract.  
Updates include:
* Adding of a Table of Contents
* Cleanup formatting to make more consistent
* Cleanup/reword some statements to make easier to understand
* Some minor reorganization of content to make it easier to understand/find
* Fix broken links
None of these changes should be controversial, as it's mostly just a lot of minor cleanup.  I'm just creating this as a PR in order to make sure the Markdown formatting is all still valid/correct once uploaded into GitHub.
=> README updates: Add TOC, reorg and cleanup formatting/language

processes-endpoint.md
This PR contains a small change to the "process" object output in rest. Currently the process only outputs the start and end time. But if multiple processes get queued, they don’t have a start or end time, so it’s difficult for a user to know when they were added or in what order. We already track the creation time in the database, this PR exposes it via the rest api.
=> [Process] Add creation time to the process rest output

epersons.md
Changes EPerson password PATCH commands to use "add" instead of "replace" 
See https://github.com/DSpace/DSpace/pull/3041 for more details.
=> Update Epersons contract per DSpace/DSpace#3041

.gitignore, README.md, authentication.md, csrf-tokens.md
This PR updates our REST Contract based on https://github.com/DSpace/DSpace/pull/3103
* Adds information about CSRF Protection to README & a new `csrf-tokens.md` page for more details
* Updates docs on Logout to note that it now requires `POST`
* Other minor cleanup to README (including removing the warning at the top) & .gitignore
=> Add information about CSRF Protection

search-endpoint.md
This RESTContract PR adds the authorityKey definition to the facet endpoint as developed in the following PR: https://github.com/DSpace/DSpace/pull/3176
=> Facet endpoint returns authorityKey

search-endpoint.md
Relates to: https://github.com/DSpace/DSpace/pull/3098
If no valid operator is passed in a filter query the discovery endpoint will now result in an unprocessable entity.
=> [search-endpoint] Adding 422 exception if the discovery operator is invalid

authentication.md
This is related to https://github.com/DSpace/dspace-angular/pull/1004#issuecomment-811875846
It adds the GET endpoint as an alternative, which is only available from the trusted IP
=> Support a short lived token using GET to deal with CSRF in Angular

claimedtasks.md, pooltasks.md
https://github.com/DSpace/DSpace/pull/3054 moved the endpoint to claim a pool task to the claimed tasks resource. The pool tasks REST contract was still mentioning the defunct endpoint.
=> BUGFIX: Reflect changes in PR #3054

bitstreams.md
This is the contract for https://github.com/DSpace/dspace-angular/issues/1147
=> Old 6.x URL paths should redirect to new 7.x location (for SEO)

items.md
Document that the `/api/core/items` endpoint only returns "archived" items & link to ticket where that bug is described in more detail. 
See also https://github.com/DSpace/DSpace/pull/3321
=> Update items contract per PR#3321

items.md, version.md, versionhistory.md
This rest contract add the capabilities to create, delete and edit versions (only the summary information).
It is aimed to introduce the needed REST API to support the implementation of all the versioning features available before DSpace 7 and required in https://github.com/DSpace/RestContract/pull/167
It is an alternative to the https://github.com/DSpace/RestContract/pull/167
Indeed, from the discussion in the other PR we get the idea to rethink our design keeping almost untouched (backward compatible) the access endpoints that were already defined.
Please note that redesigning the endpoint and having learned some caveau from the first draft implementation that we had started https://github.com/DSpace/DSpace/pull/3371 we noted that it was required to detail better the security for these …
=> Complete the version and version history endpoints

relationships.md, relationshiptypes.md
This PR is the result of the discussion in https://github.com/DSpace/RestContract/pull/165
It provides an additional search methods for the relationship endpoint that will avoid the need to introduce a new type of projection.
Please note that the change in the relationshiptypes endpoint is very similar to the one in the above PR with the difference that the entity name is used as search parameter. This should in our opinion avoid a request in the scenario that need to be supported on the angular UI (DSpace/dspace-angular#1148) as the UI already know the item where the admin need to manage the relationships, this mean that the entity label is known but not necessary the Id. The entity label is de-facto a business id that cannot change in a easy way as it is stored in the item metadata.
=> Additional search methods for relationships

browses.md
- Needed for https://github.com/DSpace/dspace-angular/issues/852
Adds a dataType property to the browse index response, in order to allow the UI to differentiate between the different types based on rest data alone.
The name "dataType" as well as the values "date", "title" and "text" have been chosen because they are already used in the configuration docs and in the api layer. DataType was simply never exposed on the REST endpoint.
I also added the "id" to the example response, as it was missing
=> Add dataType property to browse index response

README.md, submission.md, workflowitems.md
This PR added a new `submission.md` which provides a higher level overview of how to create, edit & complete a Submission.  
This can be used as a guide for others to better understand how to interact with our REST API to deposit content into DSpace, especially since you have to interact with a number of endpoints to complete a submission.
Also includes minor updates to WorkflowItem docs (see `workflowitems.md`) to update/correct the documentation based on the current behavior of this endpoint.
=> Add some better Submission documentation to our RestContract

version.md
This is just to remove the warning that versioning is not supported with entities. This is supported using https://github.com/DSpace/DSpace/pull/8265
This should be merged after https://github.com/DSpace/DSpace/pull/8265
=>  Feature relationship versioning: remove warning

epersons.md
Fixes: https://github.com/DSpace/DSpace/issues/8254
REST: https://github.com/DSpace/DSpace/pull/8404
Angular: https://github.com/DSpace/dspace-angular/pull/1776
=> Make password minimum requirements stronger

authentication.md
We need to provide the CSRF token as a header and as a cookie.
Closes #209
Note: these docs are also a bit messy and difficult to read. I had to stop myself from fixing spelling mistakes, formatting, and language. If I get time I'll submit something to improve them...
=> authentication.md: add note about XSRF cookie

items.md, supervisionorders.md, workspaceitems.md
Rest contract for Supervision Orders resource, defined in https://github.com/DSpace/DSpace/issues/2878 . 
We decided, during creation, to pass all parameters in query string since they are not attributes of the supervision order entity but references (item id and group id) and indications about how to behave (type), see https://github.com/DSpace/RestContract#on-collection-of-resources-endpoints
=> contract for supervision orders endpoint

submission.md
Fixed the typo in `workspaceitems.md` (previously: `workspaceitem.md`)
=> Fix workspaceitems.md path

items.md
Expanded description of OwningCollection section to include inheritPolicies parameter for the move item operation.
Requires DSpace/dspace#8717
=> Include description of inheritPolicies parameter in move item op

browses.md
This PR adds compatibility for controlled vocabularies in the browse pages.
It includes a link to the browse vocabulary to display the tree, and the name of the facet to filter the items
=> Browse by support for Controlled Vocabulary

entitytypes.md
entitytypes.md still referred to "item types" in the descriptions and example data in various places, and used outdated example REST API URLs.
This PR fixes those references.
=> Fix outdated references and example URLs in entitytypes.md

README.md, bitstreamformats.md, bitstreams.md, browses.md, bundles.md, claimedtasks.md, collections.md, communities.md, entitytypes.md, epersongroups.md, epersons.md, external-authority-sources.md, harvestermetadata.md, item-requests.md, items.md, itemtemplates.md, metadatafields.md, metadataschemas.md, orcidhistories.md, relationships.md, relationshiptypes.md, search-endpoint.md, supervisionorders.md, vocabularies.md, workflowitems.md, workflowsteps.md, workspaceitem-data-license.md, workspaceitem-data-upload.md, workspaceitems.md
This is somewhat aesthetic but also ensures that at least the base URL and paths in all our example requests goes to a live, working DSpace 7 REST API endpoint.
* Replaced broken URLs related to dspace7-entities.atmire.com
* Replaced broken URLs related to dspace7-internal.atmire.com
* Replaced broken URLs related to an unkonwn IP
* Replaced broken URLs related to dspace7.4science.cloud
* For completeness and to match demo server, replaced dspace7.4science.it URLs even though they're not broken
* LEFT the localhost URLs in the readme, but perhaps we should change them too?
* LEFT the `${dspace.server.url}` variables as they indicate a variable nicely
* Replaced all broken /dspace-spring-rest/ paths with /server/
Perhaps api7.dspace.org could instead itself be replaced by that variable? …
=> Update all example urls

authentication.md, bitstreamformats.md, bitstreams.md, browses.md, bundles.md, claimedtasks.md, collections.md, communities.md, entitytypes.md, epersongroups.md, epersons.md, external-authority-sources.md, harvestermetadata.md, item-requests.md, items.md, itemtemplates.md, metadatafields.md, metadataschemas.md, orcidhistories.md, relationships.md, relationshiptypes.md, resourcepolicies.md, search-endpoint.md, supervisionorders.md, vocabularies.md, workflowitems.md, workflowsteps.md, workspaceitem-data-license.md, workspaceitem-data-upload.md, workspaceitems.md
Replace references to api7.dspace.org with demo.dspace.org now that the demo server is running DSpace 7.
=> Replace references to api7.dspace.org

configuration.md
Reverts DSpace/RestContract#243
As was noted in today's meeting by @J4bbi , I misunderstood the original PR.  I had thought it was a fix to incorrect documentation, but I now realize that the original contract was related to https://github.com/DSpace/DSpace/issues/9014 ... which is a larger change needing review.
=> Revert "Return no content for unset properties"

epersongroups.md, epersons.md
(Replaces #237)
Required by https://github.com/DSpace/DSpace/issues/9052 and https://github.com/DSpace/dspace-angular/issues/2512
In order to fix the performance issues described in the above tickets, we need a way to search across _all Groups_ and _all EPersons_ which are **not yet a member of** a specific Group in the system.
Therefore, this PR suggests two new REST API endpoints:
1. `GET /api/eperson/groups/search/isNotMemberOf?group=<:uuid>&query=<:string>`
* Will search across all Groups which are not yet a member of the Group specified by `group=<:uuid>`.
* This is the same as searching all Groups which are NOT listed under the `/api/eperson/groups/<:uuid>/subgroups` endpoint for that Group specified by `group=<:uuid>` 
2. `GET …
=> Contract for `isNotMemberOf` searches for Groups and EPersons

.github/workflows/issue_opened.yml, .github/workflows/label_merge_conflicts.yml, .github/workflows/port_merged_pull_request.yml, .github/workflows/pull_request_opened.yml
This PR only updates GitHub Actions to add more automation to RestContract repo.
* Add ability to port PR between branches to allow us to version REST Contract (there is now a `dspace-7_x` branch for 7.x and a `main` for 8.x)
* Add label merge conflicts action to add `merge conflict` label to conflicting PRs
* Add action to assign PRs back to their creator (just makes creator easier to see on Project boards)
* Minor updates to existing action
No changes to the actual REST contract were made.
=> Sync GitHub actions with other repos (DSpace & dspace-angular)

processes-endpoint.md
* Related to DSpace/dspace#9295
This PR updates the possible sort options for `/processes/search/byProperty`, as described in the REST PR above.
Note: I didn't have to add `creationTime` to the output examples as it was already there, even though this [isn't the case](https://demo.dspace.org/server/#https://demo.dspace.org/server/api/system/processes) at the moment.
=> New 'creationTime' sort option for '/search/byProperty' in processes contract

workspaceitem-data-upload.md
Related to https://github.com/DSpace/DSpace/issues/8834
The modification allows to expose the primary bitstream of the ORIGINAL bundle in the upload section of workspace/workflow item so that it can be eventually set during the submission process
=> CST-12041 add support to set primary bitstream in the submission

correctiontypes.md, qualityassuranceevents.md
**Please note that this development has been funded by the University of California - California Digital Library.**
This PR  adds the endpoints required to implement a "DSpace Users" driven quality assurance source named "DSpace User Corrections". This gives the possibility to create quality assurance event, retrieve quality assurance event created by the current user and delete them.
The DSpace User Corrections manage different types of correction providing future proof extensibility that can be discovered via the proposed new REST API correctiontypes endpoint.
The REST and Angular PRs are following that will use this new endpoint to provide the ability for authorized users to request withdrawal or reinstate of an item managing the request within DSpace instead than rely on email or …
=> Add support for a DSpace internal quality assurance source

identifiers.md
Fix minor Markdown syntax issue in `identifiers.md`.
=> identifiers.md: fix Markdown link

epersons.md
The description in `epersons.md` does not cover the case that the given email address does not belong to any EPerson.
=> updated description of API endpoint /eperson/epersons/search/byEmail

workspaceitem-data-upload.md
=> Remove references to unsupported access condition operations for WSI upload

collections.md, communities.md, items.md
- Added missing required body parameters to collection PUT request
- Removed unnecessary body parameters from community/collection/item PUT requests. These were parameters that can't be updated with a PUT request and who aren't necessary to perform the request.
=> Added missing required collection body parameters to PUT request

csrf-tokens.md
Documentation for the new `GET /api/security/csrf` endpoint added by https://github.com/DSpace/DSpace/pull/9321
* In that PR, this endpoint is currently only necessary for ITs related to CSRF tokens because Spring Security 6 doesn't support cookie-based CSRF creation in its integration test tools. 
* It also is used to fix https://github.com/DSpace/DSpace/issues/9236  (see https://github.com/DSpace/dspace-angular/pull/2886 and https://github.com/DSpace/dspace-angular/pull/2897)
Adding more details to the documentation on CSRF Token behavior, by including details on how the User Interface interacts with the REST API with regards to CSRF tokens.
=> New `/api/security/csrf` endpoint & updated CSRF docs

items.md
Expose the item submitter over the REST
=> [Contract] Expose the item submitter over the REST endpoint `/api/core/items/<:uuid>/submitter`

epersonregistrations.md, epersons.md
---
dspace-8_x version DSpace/RestContract#293
dspace-7_x version DSpace/RestContract#292
This PR contains changes needed to improve the login flow for the ORCID Authorization feature.
* Fixes DSpace/DSpace#9087
=> Enhanced Login flow for ORCID Authorization feature

captcha.md, endpoints.md
* DSpace PR: https://github.com/DSpace/DSpace/pull/10407
* Angular PR: https://github.com/DSpace/dspace-angular/pull/3984
This pull request documents the new REST API endpoint for creating ALTCHA captcha challenge payloads, used in the request-a-copy form.
=> Request-a-copy: ALTCHA challenge endpoint doc

metadata-patch.md
Currently, metadata PATCH requests with `"op": "replace"` and an unknown metadata field in the `path` are treated as if they have `"path": "/metadata"`. This can lead to unexpected loss of metadata as detailed in https://github.com/DSpace/DSpace/issues/10817
This PR documents the changes made in https://github.com/DSpace/DSpace/pull/10961 to resolve this problem: any unknown field in the `path` will immediately lead to an HTTP 422 response.
The change affects all PATCH operations, to avoid similar problems.
=> Explain metadata registry requirement for PATCH paths
