search-endpoint.md
search-rels.md

This PR adds a contract definition for the discovery search and facet endpoints.

Discovery search endpoint

---

search-endpoint.md

This PR is to align the contract with the implementation in https://github.com/DSpace/DSpace/pull/1881

DS-3489: Align contract with implementation

---

endpoints.md
item-requests.md

https://jira.duraspace.org/browse/DS-3952

[DS-3952] Expose Request Copy

---

README.md

#27 Document endpoint naming rules

---

items.md

This PR will cover adding an item in the rest api (bypassing the workflow) and modifying the metadata through a PUT request.
The updates will currently work with PUT as a framework for PATCH is still in the works.
This PR can be considered work in progress as it will have the same issues as the comm/coll crud: https://github.com/DSpace/Rest7Contract/pull/33
JIRA: https://jira.duraspace.org/browse/DS-4108

Item CRUD contract changes

---

collections.md
communities.md

This PR includes alterations to the community / collection to support creating, updating & deleting communities / collections.
The update currently uses PUT as a framework for PATCH is still in the works.

Updating collections & communities rest contracts

---

relationships.md

This extends the configurable entities REST contract with CRUD operations on the relationships to create, update and delete a relationship
This is an extension to https://github.com/DSpace/Rest7Contract/pull/40

Entities crud relationships

---

bitstreamformats.md
endpoints.md

This PR details the GET for bitstreamformats (but with fixes to include the correct supportLevel and extensions)
It also details the contract for the POST, PUT and DELETE to update the bitstreamformat

CRUD support for bitstream formats

---

submissionforms.md

This PR is not to perform any changes to REST.
It rather updates the sample output with the actual data returned by REST based on the current master code
It also creates valid JSON

Updating submissionforms sample output with actual data

---

items.md

Support for uploading a bitstream to an archived item (outside the workspace/workflow)
The contract for uploading a file combined with JSON properties is based on https://stackoverflow.com/questions/21329426/spring-mvc-multipart-request-with-json/25183266#25183266

upload bitstream to archived item

---

collections.md

The Rest contract for retrieving the mapped items in a collection introduced in https://github.com/DSpace/DSpace/pull/2282

mapped items in a collection

---

authorities.md

This PR documents the authority control implementation based on the current implementation
There are still bugs in the REST implementation, this PR is just making sure the current implementation is documented

Authority control Rest contract

---

items.md
relationships.md

Support for populating related items with static metadata based on the virtual metadata when an item or relationship is deleted.

Delete item with relationships

---

collections.md

Retrieve, create, update, delete Item template

CRUD on Collection Item template

---

collections.md
communities.md

Retrieve, create, replace, delete logo

CRUD on Collection & Community logo

---

bitstreams.md
collections.md

Moving DELETE of collection logo to bitstream REST endpoint
Removing the PUT on collection logo

Collection logo

---

collections.md
endpoints.md
itemtemplates.md

Moving PATCH and DELETE of item templates to separate REST endpoint

collection item template

---

bundles.md

Small updates to the bundle REST Contract, primarily the DELETE was missing

bundle DELETE contract

---

bitstreamformats.md
bitstreams.md
bundles.md
collections.md
communities.md
items.md
itemtemplates.md
metadatafields.md
metadataschemas.md
relationships.md

this is related to https://jira.lyrasis.org/browse/DS-4392

DS-4392 fix inverted labels for 401 and 403 error codes

---

endpoints.md
patch.md
resourcepolicies.md

This is the proposal for the resourcepolicies endpoint fixing some previous inconsistency that were already identified in https://github.com/DSpace/DSpace/pull/2447
Details about how to create, search, delete and modify the resourcepolicy has been added as well

Contract for the resourcepolicies endpoint

---

authorizations.md
resourcepolicies.md

This is to clarify what agreed in https://github.com/DSpace/DSpace/pull/2604#discussion_r375521780

Clarify how to deal with anonymous requests

---

projections.md

This PR is related to https://github.com/DSpace/DSpace/pull/2670
It documents the new embed parameter

Projections embedding

---

workflowitems.md

Administer Workflow requires:
* Abort WorkflowItem: already supported
* Delete WorkflowItem: new in this PR
* Send back to Submitter: same as Abort WorkflowItem

Administer Workflow

---

communities.md

As by discussion in: https://github.com/DSpace/DSpace/pull/2707#discussion_r393095824

Remove subCommunties search method

---

scripts-endpoint.md

Adding "nameLong" & "mandatory" attributes to the script options.

[Scripts & processes] Adding "nameLong" & "mandatory" attributes

---

epersonregistrations.md
epersons.md

Rest contract to request a token for the New User Registration & Forgot password
Rest contract to create the new user or update the password of an existing user based on the token

New User Registration & Forgot password

---

epersonregistrations.md

Minor bugfix to PR #117 
After renaming the URL from epersonregistrations to registrations, the type property was not updated

New User Registration & Forgot password: minor update

---

configuration.md

Contract to retrieve configuration parameters from the local.cfg.

Configuration property retrieval

---

authentication.md

As identified in the issue: https://jira.lyrasis.org/browse/DS-4464, logout process should also support 302 Found for the logout page.

Minor Logout changes to support Logout Page

---

collections.md

Small changes to the contract to include the features introduced in DS-4504
https://github.com/DSpace/DSpace/pull/2771#discussion_r434593037

DS-4504 Performance issues with finding Collections a user can submit to

---

claimedtasks.md
pooltasks.md

Updated rest contract related to this PR: https://github.com/DSpace/DSpace/pull/3054

Update claimedtasks and pooltasks to support reloading of workflow actions on individual WorkflowItems

---

submissionforms.md

This is the REST contract for https://github.com/DSpace/dspace-angular/issues/943
This adds the externalSources property.
It also fixes a few minor inconsistencies in the contract.

Limit externalSources per metadata field

---

submissionuploads.md
workflowitems.md
workspaceitem-data-upload.md
workspaceitems.md

Based on https://github.com/DSpace/dspace-angular/issues/869, the changes in this PR will need to be applied to the REST Contract

Submission embargo bug

---

bitstreamformats.md

see https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

correct error codes

---

bitstreams.md
items.md

This is related to https://github.com/DSpace/DSpace/issues/3286

Link to thumbnails from REST

---

items.md

Described the changes done in https://github.com/DSpace/DSpace/pull/3264 required by https://github.com/DSpace/DSpace/issues/3245

Add more details about the single item endpoint and withdrawn items

---

endpoints.md
feedbacks.md

We are opening this PR with the proposed Rest Contract to collect submission of Feedback form, discussed in https://github.com/DSpace/DSpace/issues/2836

Feedback form rest contract

---

browses.md

Update REST contract so matches changes done in https://github.com/DSpace/DSpace/pull/8210

Update browse startsWith param description

---

authentication.md

Rest Contract for https://github.com/DSpace/DSpace/issues/8206
Add details about the special groups in the status endpoint

Add details about the special groups

---

collections.md

See https://github.com/DSpace/DSpace/pull/8286

Document 422 response for DELETE workflow role Group

---

resourcepolicies.md

Fixes #https://github.com/DSpace/DSpace/issues/8277
Angular PR: #https://github.com/DSpace/dspace-angular/pull/1641
REST PR: #https://github.com/DSpace/DSpace/pull/8287

Allow to do group/eperson patching of a resourcepolicy

---

relationships.md

This small RestContract PR contains the update in response example proposed with issue [#7984](https://github.com/DSpace/DSpace/issues/7984)

RelationshipType embedding from relationships

---

actuator.md
endpoints.md

This PR is related to https://github.com/DSpace/DSpace/pull/8166 and simply add the list of the default enabled actuators on the endpoints contract

[CST-5288] Added spring boot actuators on endpoints contract

---

submissionsection-types.md
workspaceitem-data-sherpa-policy.md

Related to https://github.com/DSpace/DSpace/issues/2840
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

Sherpa-Romeo Integration Rest Contract

---

endpoints.md
profiles.md

This PR add the update of ORCID synchronization preferences on profiles endpoint.
Includes https://github.com/DSpace/RestContract/pull/180
Related to https://github.com/DSpace/DSpace/pull/8263
REVIEWERS: Here's a diff of what is unique in this PR  https://github.com/DSpace/RestContract/compare/4Science:CST-5347...4Science:CST-5590

Update ORCID synchronization preferences

---

endpoints.md
orcidhistories.md
orcidqueues.md

Rest contract for orcid queue and orcid history endpoints (related to https://github.com/DSpace/DSpace/pull/8266)

Orcid queue and orcid history contract

---

epersons.md

Related to https://github.com/DSpace/DSpace/issues/8255
This PR modify the REST contract for the update of the eperson's password adding the challange to be checked

Ask current password to user when he / she sets a new password

---

vocabularies.md

This is in relation to [PR#8600](https://github.com/DSpace/DSpace/pull/8600)

Remove authentication of vocabularies endpoint

---

epersonregistrations.md

Contract changes related to PR: https://github.com/DSpace/DSpace/pull/8619

97298: Self register domain restriction changes

---

endpoints.md
systemwidealerts.md

Adds system-wide alerts to the REST contract
REST: https://github.com/DSpace/DSpace/pull/8624
Angular: https://github.com/DSpace/dspace-angular/pull/2025
The REST side is still a WIP, so this PR may still change to match

System-wide alerts

---

endpoints.md
identifiers.md
items.md
submissionsection-types.md
workspaceitem-data-identifiers.md
workspaceitems.md

_Attribution: Donated by The Library Code with the support of Technische Universität Hamburg and Technische Informationsbibliothek_
REST Contract changes to document and provide examples for the **identifier** section and sectionType.
Related to DSpace/DSpace#8423
Related to DSpace/dspace-angular#1740

[TLC-249] Identifier section REST Contract documentation

---

workflowactions.md

Contract changes with examples for the advanced workflow steps
Related REST PR: https://github.com/DSpace/DSpace/pull/8629

Advanced workflow steps

---

.github/workflows/issue_opened.yml
subscriptions.md

Rest contract for Subscription feature, defined in issue https://github.com/DSpace/DSpace/issues/2871

Subscription feature rest contract

---

scripts-endpoint.md

Reference: https://github.com/DSpace/DSpace/pull/8735

DS-8668: updated status codes to include new 413 response when uploaded file exceeds the configured limit

---

authentication.md

minor improvements in authentication.md

---

item-requests.md

Related to: https://github.com/DSpace/DSpace/pull/8795

DS-8636 - Security issue, request item token should not be exposed

---

README.md
bitstreams.md

Related to https://github.com/DSpace/DSpace/pull/8485
This is the REST Contract that'll allow the REST api to delete multiple bitstreams with a single request

REST Contract for the delete multiple bitstreams endpoint

---

metadatafields.md
metadataschemas.md

REST Contract for PR https://github.com/DSpace/DSpace/pull/8758
This includes the return codes for the Metadata Fields & Schemas endpoints

Added return codes to the Metadata Schemas & Fields Endpoints

---

bundles.md

Fixes https://github.com/DSpace/dspace-angular/issues/1578
REST Implementation: https://github.com/DSpace/DSpace/pull/8876

Primary bitstream

---

signposting.md

Updates REST Contract related to the implementation of Signposting https://github.com/DSpace/DSpace/pull/8905

[DURACOM-156] Singposting: feedback after initial deployment

---

search-endpoint.md

Link to DSpace 7 docs instead of DSpace 6!

search-endpoint.md: link to DSpace 7 docs

---

profiles.md

Fixes #255 for details about the mentioned files

replace orcid profile synchronization preferences - fundings instead of projects

---

relationships.md

- Issue DSpace/dspace-angular#1387
- DSpace/DSpace#9621
Added documentation for the new `relatedEntityType` to the `/server/api/core/relationships/search/byLabel` endpoint

Added new relatedEntityType parameter to the relationships search byLabel endpoint

---

items.md

Update of the issue link as all DSpace issues were moved from Jira to Github.

items.md: update issue link

---

collections.md

fixes typo on REST End-Points (#295)

---

search-endpoint.md

this documents the changes added by PR https://github.com/DSpace/DSpace/pull/10169, examples and further information about the information delivered about some facet in the REST-API
https://github.com/DSpace/DSpace/issues/9404

searchFacet openByDefault API docs
